[package]
name = "vm"
version = "0.1.0"
authors = ["AndrÃ© Oliveira <p32blo@gmail.com>"]

[dependencies]
clap = { version = "2", default-features = false }
unescape = "0.1"
error-chain = { version = "0.7", default-features = false }
